{% set name = "apriltag" %}
{% set version = "3.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AprilRobotics/apriltag/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a5f890a1406469fde4dabf92042072cac68b38db9b4aaf78316aca7c5fc2c9d8
  patches:
    - 377.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('apriltag', max_pin='x.x.x') }}
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - pkg-config
    - ninja
  host:
    - python
    - numpy
  run:
    - python

test:
  requires:
    - {{ compiler('c') }}
    - cmake
    - ninja
    - python
  files:
    - CMakeLists.txt
    - test.c
  commands:
    - cmake -G Ninja -B build_test
    - cmake --build build_test
    - python -c "from apriltag import apriltag"  # [linux]

about:
  home: https://github.com/AprilRobotics/apriltag
  summary: 'AprilTag is a visual fiducial system popular for robotics research.'
  description: |
    AprilTag is a visual fiducial system popular in robotics research. This repository
    contains the most recent version of AprilTag, AprilTag 3, which includes a faster
    (>2x) detector, improved detection rate on small tags, flexible tag layouts, and
    pose estimation. AprilTag consists of a small C library with minimal dependencies.
  license: BSD-2-Clause-Views
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - christian-rauch
